### ISSUE TITLE
Refit.Exception when deserializing using System.Text.Json

### ISSUE THREAD

**Issue by jagnarock** [reactiveui/refit#1128]
When using Refit with System.Text.Json and the SystemTextJsonContentSerializer the following error comes up:
Refit.ApiException: An error occured deserializing the response.
 ---> System.Text.Json.JsonException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)

This happens when the API returns StatusCodeResult (eg. return NoContent(), return StatusCode(204).
When returning StatusCodeResult the HttpContentHeaders in HttpContent are empty and the MediaTypeHeaderValue is null and the content itself has no content to deserialize and an exception in System.Text.Json is thrown.
![image](https://user-images.githubusercontent.com/53445366/111761170-df273b80-889f-11eb-9626-bac05390e38d.png)

My Suggestion is to change the FromHttpContentAsync method to:
`public async Task<T?> FromHttpContentAsync<T>(HttpContent content, CancellationToken cancellationToken = default)
        {
            if(content.Headers.ContentType != null && content.Headers.ContentType.MediaType == "application/json")
            {
                var item = await content.ReadFromJsonAsync<T>(jsonSerializerOptions, cancellationToken).ConfigureAwait(false);
                return item;
            }

            return default;
        }`

**Comment by LaurensAdema** [comment]
We're encountering the same issue on 204 requests. Is there a (temporary) workaround possible?

**Comment by jagnarock** [comment]
> We're encountering the same issue on 204 requests. Is there a (temporary) workaround possible?

What I did as workaround so far:
I created a 'CustomContentSerializer', implement the IHttpContentSerializer and in the FromHttpContentAsync method I added the check.
Here is a sample of how you could implement a Serializer on your own (the implementation is from Refit, I just added the additional check): 

`

     public class CustomContentSerializer : IHttpContentSerializer 

        private readonly JsonSerializerOptions jsonSerializerOptions;

        public CustomContentSerializer() : this(new JsonSerializerOptions(JsonSerializerDefaults.Web))
        {
            jsonSerializerOptions.DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull;
            jsonSerializerOptions.ReferenceHandler = ReferenceHandler.Preserve;
            jsonSerializerOptions.WriteIndented = true;
            //jsonSerializerOptions.IgnoreNullValues = true;
            jsonSerializerOptions.PropertyNameCaseInsensitive = true;
            jsonSerializerOptions.PropertyNamingPolicy = JsonNamingPolicy.CamelCase;
            jsonSerializerOptions.Converters.Add(new ObjectToInferredTypesConverter());
            jsonSerializerOptions.Converters.Add(new JsonStringEnumConverter(JsonNamingPolicy.CamelCase));
        }

        public CustomContentSerializer(JsonSerializerOptions jsonSerializerOptions)
        {
            this.jsonSerializerOptions = jsonSerializerOptions;
        }

        public async Task<T?> FromHttpContentAsync<T>(HttpContent content, CancellationToken cancellationToken = default)
        {
            if(content.Headers.ContentType != null && content.Headers.ContentType.MediaType == "application/json")
            {
                var item = await content.ReadFromJsonAsync<T>(jsonSerializerOptions, cancellationToken).ConfigureAwait(false);
                return item;
            }

            return default;
        }

        public string? GetFieldNameForProperty(PropertyInfo propertyInfo)
        {
            if(propertyInfo is null)
            {
                throw new ArgumentNullException(nameof(propertyInfo));
            }

            return propertyInfo.GetCustomAttributes<JsonPropertyNameAttribute>(true)
                       .Select(a => a.Name)
                       .FirstOrDefault();
        }

        public HttpContent ToHttpContent<T>(T item)
        {
            var content = JsonContent.Create(item, options: jsonSerializerOptions);
            return content;
        }

        // From https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to?pivots=dotnet-5-0#deserialize-inferred-types-to-object-properties
        public class ObjectToInferredTypesConverter
           : JsonConverter<object>
        {
            public override object? Read(
              ref Utf8JsonReader reader,
              Type typeToConvert,
              JsonSerializerOptions options) => reader.TokenType switch
              {
                  JsonTokenType.True => true,
                  JsonTokenType.False => false,
                  JsonTokenType.Number when reader.TryGetInt64(out var l) => l,
                  JsonTokenType.Number => reader.GetDouble(),
                  JsonTokenType.String when reader.TryGetDateTime(out var datetime) => datetime,
                  JsonTokenType.String => reader.GetString(),
                  _ => JsonDocument.ParseValue(ref reader).RootElement.Clone()
              };

            public override void Write(
                Utf8JsonWriter writer,
                object objectToWrite,
                JsonSerializerOptions options) =>
                JsonSerializer.Serialize(writer, objectToWrite, objectToWrite.GetType(), options);
        }
    }
`

And in Startup.cs:
`
               services.AddHttpClient("CoilDNATenantClient", c => c.BaseAddress = new Uri(Configuration["Endpoints:Tenant"]))
                .AddTypedClient(c => RestService.For<ITenantClient>(c, new RefitSettings
                {
                    //https://github.com/reactiveui/refit/blob/main/Refit/SystemTextJsonContentSerializer.cs
                    //ContentSerializer = new SystemTextJsonContentSerializer(new JsonSerializerOptions(JsonSerializerDefaults.Web)
                    //{
                    //    IgnoreNullValues = true,
                    //    ReferenceHandler = ReferenceHandler.Preserve,
                    //    WriteIndented = true
                    //})
                    ContentSerializer = new CustomContentSerializer()
                }));
`

**Comment by LaurensAdema** [comment]
Thanks for the help and quick response!

**Comment by CleytonGoncalves** [comment]
Any news on this issue? Affecting us as well.

**Comment by clairernovotny** [comment]
Unfortunately this fix is more complicated than here. We can't return `null` or `default` for non-nullable return types. A 204 returns null, effectively. That means we have to detect if the return type is non-nullable or nullable so we can either return null or throw. 

Another workaround is to use `ApiResponse<>` or `HttpResponseMessage` return types where you can check the status before deserializing the object.

**Comment by victorsimas** [comment]
I have find a way to correct this problem by detecting on my custom httpClientHandler if the content received was null or a string.Empty, on those cases i transformed it to a JSON null object, that would be a string "null", this came as a correction because of .NET 5 upgrade, that it wont give you a null content never, just an empty string.

`                    
if (string.IsNullOrEmpty(response.Content?.ReadAsStringAsync(ct).Result))
{
    response.Content = new StringContent(
        "null",
        Encoding.UTF8,
        MediaTypeNames.Application.Json);
}
`

**Comment by tjmcnaboe** [comment]
Thank you @jagnarock your workaround was helpful

**Comment by DsAekb** [comment]
> Unfortunately this fix is more complicated than here. We can't return `null` or `default` for non-nullable return types. A 204 returns null, effectively. That means we have to detect if the return type is non-nullable or nullable so we can either return null or throw.
> 
> Another workaround is to use `ApiResponse<>` or `HttpResponseMessage` return types where you can check the status before deserializing the object.

Using `ApiResponse<>` doesn't help much because it still has `Error` set in the case of 204 and this becomes cumbersome to distinct real errors from 204. Also regarding the suggested solution, it would work fine for `ApiResponse<>` as it has its `Content` as nullable, could it be used at least for this case?

**Comment by hubocan** [comment]
I agree that Refit should work as previous version when the Newtonsoft was used.

The only problem is, that Refit tries to deserialize content when there is no content and that is wrong. Returning null or default seems the best result.

**Comment by rndfm** [comment]
We are seeing this issue only on our Azure environment.
It works as expected when we try to debug the issue on our development pc's.


Refit.SystemTextJsonContentSerializer is thowing a JsonReaderException when getting a 204 no content from the service.
![image](https://user-images.githubusercontent.com/46886958/135996572-9ba453e3-8203-4d60-8062-56bebc86ffd9.png)

But on my local development machine it works just fine and i get a null value as expected.

**Comment by mbikodusic** [comment]
Do we have any update related to this?

We recently migrated our project to .NET Core 6 and Refit 6.1.15 and are facing the same issue.

**Comment by R4cOOn** [comment]
We also hit the same issue when we updated our library.

Any ETA when this will be fixed? 
It's a showstopper for us.

**Comment by LarsWesselius** [comment]
Not sure why this is not fixed yet - a possible solution was already proposed in https://github.com/reactiveui/refit/pull/1190 but was closed for reasons I don't understand. The solution in there seems viable to me (also OPs), there should be no situation in which you can't return default on a 204 because the content serializers' return type is `T?`. Or I'm missing something?

Either way whether it's a good fix or not, it is currently a clear breaking change that you'll hit if you potentially return null from your API methods.

**Comment by wrkntwrkn** [comment]
Also interested in a fix for this.

**Comment by MaksymShuldiner** [comment]
Are there any updates regarding this issue?

**Comment by rndfm** [comment]
This is causing a lot of problems in our systems. We are integrating to a service that uses 204 no content for a lot of endpoints.

**Comment by rndfm** [comment]
Workaround when an API send 204 no content.

Add a try catch around the refit call.
try
{
  // Refit call goes here.
}
catch (Refit.ApiException ex) when (ex.StatusCode == HttpStatusCode.NoContent)
{
  // Do something. Ex return empty/null/empty array
}

**Comment by jagnarock** [comment]
It seems like that the issue still exists in Version 6.3.2.
To solve, I think the method From HttpContentAsync should lool like the following:

`

     public async Task<T?> FromHttpContentAsync<T>(HttpContent content, CancellationToken cancellationToken = default)
    {
           return content.Headers.ContentType?.MediaType == "application/json"
                 ? await content.ReadFromJsonAsync<T>(jsonSerializerOptions, cancellationToken).ConfigureAwait(false)
                  : default;
    }
`

When deserializing NoContent or HTTPStatusCodeResult 204 the HttpContentHeaders in HttpContent are empty and the MediaTypeHeaderValue is null. The content itself has no content to deserialize and an exception in System.Text.Json is thrown.

**Comment by yohny** [comment]
any progress on this issue? this is quite a blocker for 204 responses

**Comment by Thorarin** [comment]
Yeah I keep having to initialize clients with serializers working around this issue; it's pretty annoying.

**Comment by Murat-Ozcan** [comment]
I am using the Refit 6.3.2 package. I found such solution and it works. I used **HttpResponseMessage** as the return type.

```
using Refit;

namespace Example.Domain.Services;

public interface IDynamicUrlApiService
{
    [Get("/users")]
    Task<HttpResponseMessage> ExistVersion1();

    [Get("/users")]
    Task<ApiResponse<HttpResponseMessage>> ExistVersion2();
}
```

**Comment by itsvse** [comment]
fix the auto 204 conversion, there's an easy workaround: You can remove the HttpNoContentOutputFormatter in Startup.cs and your ConfigureServices()method:

```
services.AddControllers(opt =>  // or AddMvc()
{
    // remove formatter that turns nulls into 204 - No Content responses
    // this formatter breaks Angular's Http response JSON parsing
    opt.OutputFormatters.RemoveType<HttpNoContentOutputFormatter>();
})
```
or

```
builder.Services.AddControllers(opt =>  // or AddMvc()
{
    // remove formatter that turns nulls into 204 - No Content responses
    // this formatter breaks Angular's Http response JSON parsing
    opt.OutputFormatters.RemoveType<HttpNoContentOutputFormatter>();
});
```

**Comment by Thorarin** [comment]
That "fixes" it on the wrong side. The HTTP spec says 200 is supposed to have content. If there is no content, the response code should be 204.

**Comment by MarcoMedrano** [comment]
Refit version 7.0.0 (at the date, last release 4 months) still same issue :( .
Notice that .net 8 has been released yesterday.

**Comment by tohidhaghighy** [comment]
use ApiResponse<> instead of only class in refit

**Comment by DominikZublasing** [comment]
Hi,
is there any update on this issue ?

**Comment by jagnarock** [comment]
> Hi, is there any update on this issue ?

Good question. We really would appreciate hearing some news from the Refit Team according this issue

**Comment by eriksteinebach** [comment]
@clairernovotny could you elaborate on why this is more complex? I totally understand the complexities about staying backwards compatible, so maybe the only solution is to give people hooks into the client to fix the problem in their specific situation? Or is there another problem here I am missing?

**Comment by eriksteinebach** [comment]
With @jagnarock 's solution I was a little worried about the maintainability long term, so I am trying out the following solution which looks like it works for us:

```
public class CustomSystemTextJsonContentSerializer : IHttpContentSerializer
{
    private SystemTextJsonContentSerializer serializer;

    public CustomSystemTextJsonContentSerializer()
    {
        serializer = new SystemTextJsonContentSerializer();
    }

    public CustomSystemTextJsonContentSerializer(JsonSerializerOptions jsonSerializerOptions)
    {
        serializer = new SystemTextJsonContentSerializer(jsonSerializerOptions);
    }

    public Task<T?> FromHttpContentAsync<T>(HttpContent content, CancellationToken cancellationToken = default)
    {
        if (content.Headers.ContentType != null && content.Headers.ContentType.MediaType == "application/json")
        {
            return serializer.FromHttpContentAsync<T>(content, cancellationToken); 
        }
        return Task.FromResult<T?>(default);
    }

    public string? GetFieldNameForProperty(PropertyInfo propertyInfo)
    {
        return serializer.GetFieldNameForProperty(propertyInfo);
    }

    public HttpContent ToHttpContent<T>(T item)
    {
        return serializer.ToHttpContent<T>(item);
    }
}
```

**Comment by derekm** [comment]
Improving on the work of @eriksteinebach & @jawa-gh -- here is my version to return null for objects and empty collections for instances of `ICollection<>`!

```csharp
public class NoContentSystemTextJsonContentSerializer : IHttpContentSerializer
{
    private readonly SystemTextJsonContentSerializer serializer;

    public NoContentSystemTextJsonContentSerializer()
    {
        serializer = new SystemTextJsonContentSerializer();
    }

    public NoContentSystemTextJsonContentSerializer(JsonSerializerOptions jsonSerializerOptions)
    {
        serializer = new SystemTextJsonContentSerializer(jsonSerializerOptions);
    }

    /// <summary>
    /// Deserializes an object of type <typeparamref name="T"/> from an <see cref="HttpContent"/> object.
    /// <para>Handles responses that don't have a response body, such as <c>204 No Content</c>.</para>
    /// </summary>
    /// <typeparam name="T">Type of the object to serialize to.</typeparam>
    /// <param name="content">HttpContent object to deserialize.</param>
    /// <param name="cancellationToken">CancellationToken to abort the deserialization.</param>
    /// <returns>
    /// The deserialized object of type <typeparamref name="T"/>.
    /// <para>If there is no response body, the response is deserialized to an empty collection for collections or <c>null</c> for objects.</para>
    /// </returns>
    public Task<T?> FromHttpContentAsync<T>(HttpContent content, CancellationToken cancellationToken = default)
    {
        // if we expect a response body, deserialize it to its type
        if (content.Headers.ContentType != null && content.Headers.ContentType.MediaType == "application/json")
        {
            return serializer.FromHttpContentAsync<T>(content, cancellationToken);
        }
        // else return empty for collections or null for objects
        Type type = typeof(T);
        if (type.GetInterfaces().Any(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(ICollection<>)))
        {
            return Task.FromResult<T?>((T)Activator.CreateInstance(type));
        }
        return Task.FromResult<T?>(default);
    }

    public string? GetFieldNameForProperty(PropertyInfo propertyInfo)
    {
        return serializer.GetFieldNameForProperty(propertyInfo);
    }

    public HttpContent ToHttpContent<T>(T item)
    {
        return serializer.ToHttpContent<T>(item);
    }
}
```

**Comment by spingee** [comment]
Any update on this? Still not work in 8.0.0

**Comment by OndrejVrsan** [comment]
> > Unfortunately this fix is more complicated than here. We can't return `null` or `default` for non-nullable return types. A 204 returns null, effectively. That means we have to detect if the return type is non-nullable or nullable so we can either return null or throw.
> > Another workaround is to use `ApiResponse<>` or `HttpResponseMessage` return types where you can check the status before deserializing the object.
> 
> Using `ApiResponse<>` doesn't help much because it still has `Error` set in the case of 204 and this becomes cumbersome to distinct real errors from 204. Also regarding the suggested solution, it would work fine for `ApiResponse<>` as it has its `Content` as nullable, could it be used at least for this case?

If you do not want to use `ApiResponse<T?>` directly, you can leverage default interface methods to hide this implementation to protected method and have public one for seamless experience.

```csharp
    [Put($"/restapi/some/path/{{{nameof(myClass)}.{nameof(MyClass.Id)}}}")]
    protected Task<IApiResponse<MyClass?>> PutMyClassInternalAsync(
        MyClass myClass,
        CancellationToken ct);

    async Task<MyClass?> PutMyClassAsync(
        MyClass myClass,
        CancellationToken ct)
    {
        var response = await PutMyClassInternalAsync(myClass, ct);
        if (response.IsSuccessStatusCode)
        {
            return response.Content;
        }

        throw response.Error;
    }
```

**Comment by tevosouza** [comment]
I worked around this issue by implementing a custom IHttpContentSerializer that safely handles empty responses (204 No Content or 200 OK with an empty body).

The main idea was to wrap `SystemTextJsonContentSerializer` and bypass deserialization when the response body is empty 

```csharp
using System.Net.Http;
using System.Reflection;
using System.Text.Json;
using Refit;

public sealed class RefitResponseJsonSerializer : IHttpContentSerializer
{
    private readonly SystemTextJsonContentSerializer _inner;
    private readonly JsonSerializerOptions _options = new JsonSerializerOptions(JsonSerializerDefaults.Web);

    public RefitResponseJsonSerializer(JsonSerializerOptions? options = null)
    {
        _inner = new SystemTextJsonContentSerializer(options ?? _options);
    }

    public async Task<T?> FromHttpContentAsync<T>(HttpContent content, CancellationToken cancellationToken = default)
    {
        if (content == null)
            return default;

        var raw = await content.ReadAsStringAsync(cancellationToken);

        if (string.IsNullOrWhiteSpace(raw))
            return default;

        return JsonSerializer.Deserialize<T>(raw, _options);
    }

    public HttpContent ToHttpContent<T>(T item)
    {
        return _inner.ToHttpContent(item);
    }

    public string? GetFieldNameForProperty(PropertyInfo propertyInfo)
    {
        return _inner.GetFieldNameForProperty(propertyInfo);
    }
}
```

Then I registered it through RefitSettings.ContentSerializer.
```csharp   
.AddRefitClient<TClient>(new RefitSettings() { ContentSerializer = new RefitResponseJsonSerializer() })
```

This allowed my API methods returning Task<T?> to correctly return null instead of throwing An error occured deserializing the response. when the API responds with no content.

```csharp
// request example with null return value (HTTP 204 No Content)
[Get("/api/user/v1")]
Task<User?> GetUserByIdAsync([Query] Guid userId);
```

It is just a workaround/bypass for now, but hopefully it helps someone else facing the same issue.

**Comment by glennawatson** [comment]
Thanks for the detailed write-up. Confirmed still reproducible in current main.

DeserializeContentAsync (src/Refit/RequestBuilderImplementation.cs) routes Task<T> through serializer.FromHttpContentAsync<T>, and SystemTextJsonContentSerializer.FromHttpContentAsync (src/Refit/SystemTextJsonContentSerializer.cs) calls ReadFromJsonAsync directly with no guard for an empty body, so a 204 (or any zero-length content) throws "The input does not contain any JSON tokens".

Correct fix needs to short-circuit before deserializing when there's no content (e.g. resp.StatusCode == NoContent, or Content-Length 0 / null Content-Type), and return default for nullable/reference return types. Keeping open; labeled bug / high / serialization.
