### ISSUE TITLE
FormBody issue with API Yet Works with Swagger.

### ISSUE THREAD

**Issue by davidbuckleyni** [reactiveui/refit#1239]
When attempting to conenct to my web api which has been secured with jwt barer token it does not authorise and returns an  error in fact it does not find the method signature.

 
My Interface 
  
    public interface ILoginAPI
     {
          [Post("/Users/")]
          Task<Token> Authenticate([Body] User user); // => parameter decorated with [Body]

    }
    public class UsersController : ControllerBase {
         [AllowAnonymous]
         [HttpPost("Authenticate")]
        public IActionResult Authenticate([FromBody] AuthenticateRequest model) {

            var response = _userService.Authenticate(model, ipAddress());
            if (response == null)
                return BadRequest(new { message = "Username or password is incorrect" });

           setTokenCookie(response.JwtToken);

            return Ok(response);
        }
     }

``This is my class to consume the above.

     public class TheHockeyLabMnHttpApi
     {
        ITheHockeyLabApi thockClubApi;
        public TheHockeyLabMnHttpApi()
        {
              thockClubApi= RestService.For<ITheHockeyLabApi>(Constants.APIUrl);
          
        }
        public List<Profile> GetAllProfile()
        {
            return hockClubApi.GetAllProfiles();
        }
     }

     public class Constants
     {
        public const string APIUrl = "https://localhost:44315/api";
      }

But when I run this through my controller

       public IActionResult Index()
       {        
            var loginAPI = RestService.For<ILoginAPI>(Constants.APIUrl);
            Token token = loginAPI.Authenticate(
              new User()
              {
                   Username = "David",
                  Password = "Test12345",
               }).Result;
        
            var mytokenHere = JsonConvert.SerializeObject(token);
            var test = token.Authenticated;            
            return View();
        }

I am new to refit so bare with me if this is something simple a saw it on johns channel one week.

System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (Response status code does not indicate success: 404 (Not Found).)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at TheHockeyLabMn.Web.Controllers.HomeController.Index() in D:\GitMaster\thehockeylabmn\TheHockeyLabMn.Web\Controllers\HomeController.cs:line 32
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()

Inner Exception 1:
ApiException: Response status code does not indicate success: 404 (Not Found).

**Comment by glennawatson** [comment]
This is a usage/routing problem, not a Refit bug. Your interface declares `[Post("/Users/")]` but the controller action is routed at `Authenticate` (`[HttpPost("Authenticate")]`), so Refit posts to `/Users/` and the server returns 404 - exactly the exception you see. Point the attribute at the real route, e.g. `[Post("/Users/Authenticate")]` (matching the controller's route template), and pass the body type the action binds (`AuthenticateRequest`).

For usage questions like this please use Discussions: https://github.com/reactiveui/refit/discussions

Closing.


<blockquote><img src="https://opengraph.githubassets.com/7da521d756b94831ff31d8d5fc75ecbe2c2d69a69928da79595847192e775278/reactiveui/refit" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/reactiveui/refit/discussions">reactiveui refit · Discussions</a></strong></div><div>Explore the GitHub Discussions forum for reactiveui refit. Discuss code, ask questions & collaborate with the developer community.</div></blockquote>
