### ISSUE TITLE
I wanna use Refit with DaprClient . any information?

### ISSUE THREAD

**Issue by a121984376** [reactiveui/refit#1337]
I use refit and DaprClient like this:

` public interface IWeatherForecast
    {
        [Get("/backend/WeatherForecast")]
        Task<String> WeatherForecast();
  }`

'
            services.AddRefitClient<IWeatherForecast>().ConfigureHttpClient(options =>
            {
                options.BaseAddress = new Uri($"http://backend-http");
            }).ConfigurePrimaryHttpMessageHandler(_ => new InvocationHandler());
'

`  var result = await this.WeatherForecast.WeatherForecast();`

but there is wrong:

System.InvalidOperationException: The inner handler has not been assigned.
   at System.Net.Http.DelegatingHandler.SetOperationStarted()
   at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Dapr.Client.InvocationHandler.<>n__0(HttpRequestMessage request, CancellationToken cancellationToken)
   at Dapr.Client.InvocationHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Refit.RequestBuilderImplementation.<>c__DisplayClass14_0`2.<<BuildCancellableTaskFuncForMethod>b__0>d.MoveNext() in /_/Refit/RequestBuilderImplementation.cs:line 256
--- End of stack trace from previous location where exception was thrown ---
   at frontend.service.Controllers.DaprController.Get_by_refit() in C:\Users\Yan\OneDrive\开发资料\Dapr\demo\frontend.service\Controllers\DaprController.cs:line 49

**Comment by a121984376** [comment]
I find solution
`                services.AddRefitClient<T>().ConfigureHttpClient(options =>
                {
                    options.BaseAddress = new Uri($"http://{appId}");
                }).AddHttpMessageHandler(_ => new InvocationHandler());`
