### ISSUE TITLE
[BUG] DelegatingHandler in Blazore Hybrid(MAUI) project throws error at IJSRuntime

### ISSUE THREAD

**Issue by nssidhu** [reactiveui/refit#1338]
**Describe the bug**

I create Blazor Hybrid (MAUI) App in Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview
Version 17.2.0 Preview 2.1
I am getting the following error with Delegating handler.
```
System.NullReferenceException: 'Object reference not set to an instance of an object.'

   at Microsoft.AspNetCore.Components.WebView.Services.WebViewJSRuntime.BeginInvokeJS(Int64 taskId, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at BlazorWasm.Client.Services.ClientTokenHttpHandler.<SendAsync>d__3.MoveNext() in C:\Users\nssid\source\repos\nssidhu\BlazorHybridAppNew\BlazorMAUI\Services\ClientTokenHttpHandler.cs:line 23
```

**Steps To Reproduce**

Here is my delegating Handler

```
public class ClientTokenHttpHandler : DelegatingHandler
	{
		private readonly ILogger<ClientTokenHttpHandler> logger;
		private readonly IJSRuntime _JsRuntime;

		public ClientTokenHttpHandler(ILogger<ClientTokenHttpHandler> logger, IJSRuntime JsRuntime)
		{
		    this.logger = logger;
			_JsRuntime = JsRuntime;
		}

		protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
		{
            try
            {
				var token = await _JsRuntime.InvokeAsync<string>("localStorage.getItem", "AuthToken");
				if (token == null)
				{
					token = "Token is Null";

				}

				//await _JsRuntime.InvokeAsync<string>("localStorage.setItem", "AuthToken","Value was set by program");

				//request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);

				request.Headers.Add("Authorization", "Bearer " + token);
				
			}
            catch (Exception ex)
            {

               Console.WriteLine(ex);
            }

			return await base.SendAsync(request, cancellationToken);
		}

	}
```
This is how i register it in program.cs

```
   var url = "https://XXXXXXXXX/";
            var setting = new RefitSettings
            {
                ContentSerializer = new SystemTextJsonContentSerializer(options)
            };

            builder.Services.AddRefitClient<IApplicationApi>(setting)
            .ConfigureHttpClient(c =>
            {
                c.BaseAddress = new System.Uri(url);
            })
            .AddHttpMessageHandler<ClientTokenHttpHandler>();

```

**Expected behavior**

IJSruntime should not throw error and be able to read Cookie from browser.

**Screenshots**

![Refit Library Error 2022-04-17_18-14-38](https://user-images.githubusercontent.com/3267605/163735692-2bf39783-b7ca-405a-80d0-c2c510a30c84.jpg)

**Environment**

- OS:        Windows 11
- Device:      
- Version:   
- Working Version: 

**Additional context**

Development environment is 
.NET 6
Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview Version 17.2.0 Preview 2.1

**Comment by anaisbetts** [comment]
This is not a bug in Refit, please file this on the .NET 6 repos
