### ISSUE TITLE
[Bug]: XML response fails to deserialize

### ISSUE THREAD

**Issue by Duoist** [reactiveui/refit#1729]
### Describe the bug 🐞

Upgrading from 7.0.0 to 7.1.0 causes previously working requests to throw the following exception:

```text
Refit.ApiException: An error occured deserializing the response.
 ---> System.InvalidOperationException: The stream was already consumed. It cannot be read again.
   at System.Net.Http.HttpConnectionResponseContent.ConsumeStream()
   at System.Net.Http.HttpConnectionResponseContent.<SerializeToStreamAsync>g__Impl|6_0(Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpContent.WaitAndReturnAsync[TState,TResult](Task waitTask, TState state, Func`2 returnFunc)
   at Refit.XmlContentSerializer.FromHttpContentAsync[T](HttpContent content, CancellationToken cancellationToken) in /_/Refit.Xml/XmlContentSerializer.cs:line 71
   at Refit.RequestBuilderImplementation.DeserializeContentAsync[T](HttpResponseMessage resp, HttpContent content, CancellationToken cancellationToken) in /_/Refit/RequestBuilderImplementation.cs:line 456
   at Refit.RequestBuilderImplementation.<>c__DisplayClass14_0`2.<<BuildCancellableTaskFuncForMethod>b__0>d.MoveNext() in /_/Refit/RequestBuilderImplementation.cs:line 384
```

### Step to reproduce

The following console application can be used to reproduce the exception.

```csharp
using System.Xml.Serialization;
using Refit;

var requestBody = """
                  <soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
                    <soap:Body>
                        <Subtract xmlns="http://tempuri.org/">
                            <intA>10</intA>
                            <intB>5</intB>
                        </Subtract>
                    </soap:Body>
                  </soap:Envelope> 
                  """;

var xmlApi = RestService.For<IXmlApi>("http://www.dneonline.com", new RefitSettings
{
    ContentSerializer = new XmlContentSerializer()
});
var response = await xmlApi.SubtractAsync(requestBody);

public interface IXmlApi
{
    [Headers("Content-Type: text/xml", "SOAPAction: http://tempuri.org/Subtract")]
    [Post("/calculator.asmx")]
    Task<EnvelopeType> SubtractAsync([Body] string request);
}

[XmlRoot(ElementName = "Envelope", Namespace = "http://schemas.xmlsoap.org/soap/envelope/")]
public class EnvelopeType
{
    [XmlElement(ElementName = "Body")] public BodyType Body { get; set; }

    public class BodyType
    {
        [XmlElement(ElementName = "SubtractResponse", Namespace = "http://tempuri.org/")]
        public SubtractResponseType SubtractResponse { get; set; }

        public class SubtractResponseType
        {
            [XmlElement(ElementName = "SubtractResult")]
            public int SubtractResult { get; set; }
        }
    }
}
```

### Expected behavior

Refit deserializes the XML response into an object.

### Refit Version

7.1.0

**Comment by ChrisPulman** [comment]
Thank you for raising this, it's possibly a side effect of #1705
