### ISSUE TITLE
[Bug]: IExampleInterface doesn't look like a Refit interface

### ISSUE THREAD

**Issue by aywee26** [reactiveui/refit#1817]
### Describe the bug 🐞

The project is ASP.NET Core Web API that uses Refit packages (Refit 7.2.0, Refit.HttpClientFactory 7.2.0, Refit.Newtonsoft.Json 7.2.0). It contacts 3rd party resource JSONPlaceholder via HTTP.

The interface IBlogApi lists several methods, all of them are annotated by appropriate Refit attributes.

```
public interface IBlogApi
{
    [Get("/posts/{id}")]
    Task<Post> GetPostAsync(int id);

    [Get("/posts")]
    Task<List<Post>> GetPostsAsync();

    [Post("/posts")]
    Task<Post> CreatePostAsync([Body] Post post);

    [Put("/posts/{id}")]
    Task<Post> UpdatePostAsync(int id, [Body] Post post);

    [Delete("/posts/{id}")]
    Task DeletePostAsync(int id);

    [Get("/posts")]
    Task<List<Post>> GetPostsAsync([Query] PostQueryParameters parameters);
}
```

The project uses source-generated implementations of these methods to provide various routes. When "GET /posts/1" query is performed, the following exception is thrown:

```
System.InvalidOperationException: IBlogApi doesn't look like a Refit interface. Make sure it has at least one method with a Refit HTTP method attribute and Refit is installed in the project.
   at Refit.RestService.GetGeneratedType(Type refitInterfaceType) in c:\temp\releaser\refit\Refit\RestService.cs:line 188
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Refit.RestService.For(Type refitInterfaceType, HttpClient client, IRequestBuilder builder) in c:\temp\releaser\refit\Refit\RestService.cs:line 79
   at Refit.RestService.For[T](HttpClient client, IRequestBuilder`1 builder) in c:\temp\releaser\refit\Refit\RestService.cs:line 19
   at Refit.HttpClientFactoryExtensions.<>c__2`1.<AddRefitClient>b__2_3(HttpClient client, IServiceProvider serviceProvider) in c:\temp\releaser\refit\Refit.HttpClientFactory\HttpClientFactoryExtensions.cs:line 87
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at lambda_method2(Closure, Object, HttpContext)
   at Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

The result is similar for other queries and commands.

### Step to reproduce

1. Clone linked reproduction repository
2. Launch the project in Debug mode
3. Perform query: GET /posts/1
4. Get error described

### Reproduction repository

https://github.com/aywee26/refit-client-example

### Expected behavior

The project should return OK response with a body similar to this: 
```
{
  "id": 1,
  "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
  "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
  "userId": 1
}
```

### IDE

Rider Windows

### Operating system

Windows

### Version

11 23H2

### Refit Version

7.2.0

### Additional information ℹ️

Current workaround: downgrade Refit packages from version 7.2.0 to 7.1.2.

**Comment by freenetbrasil** [comment]
Same here; I had to downgrade to 7.1.2

**Comment by TimothyMakkison** [comment]
Thanks for the example repository, this looks pretty severe. I don't see any implementations of `IBlogApi` or even `partial class Generated` being created. Looks like the source generator isn't running.

@ChrisPulman any idea what has changed since 7.1.2 to cause this?

**Comment by ChrisPulman** [comment]
![image](https://github.com/user-attachments/assets/69727a15-aa16-4003-8720-de6413758296)

**Comment by ChrisPulman** [comment]
This was run using VS2022 V17.11.3, sorry, I don't have Rider to test with.

**Comment by ChrisPulman** [comment]
> Thanks for the example repository, this looks pretty severe. I don't see any implementations of `IBlogApi` or even `partial class Generated` being created. Looks like the source generator isn't running.
> 
> @ChrisPulman any idea what has changed since 7.1.2 to cause this?

@TimothyMakkison Do you have Rider? If so, does this issue occur when you run it?

**Comment by TimothyMakkison** [comment]
I think the issue is 29e0e1ce.

**Comment by ChrisPulman** [comment]
@TimothyMakkison Thank you Tim, strange that it only affects Rider.

**Comment by TimothyMakkison** [comment]
I'm guessing you are on the latest version of Visual studio where they support `Microsoft.CodeAnalysis.CSharp` 4.11.0, Rider might still be on 4.10.0

**Comment by flojon** [comment]
I get the same problem using Visual Studio 2022. Didn’t update VS in a while. Will try that tomorrow.18 sep. 2024 kl. 22:20 skrev Tim M ***@***.***>:﻿
I'm guessing you are on the latest version of Visual studio where they support Microsoft.CodeAnalysis.CSharp 4.11.0, Rider might still be on 4.10.0 hence why nothing is generated.

**Comment by ChrisPulman** [comment]
Please update to 7.2.1 this issue should be resolved, thank you

**Comment by aywee26** [comment]
I've updated Rider to the latest version (RD-242.21829.210), set Refit version to 7.2.0 (aka the problematic one), performed actions "Build selected project", "Build selected project", launched it in Debug mode and the issue is magically gone.
The more you know, I guess.

**Comment by flojon** [comment]
7.2.1 works good for me. Thanks!
