### ISSUE TITLE
[Bug]: MissingMethodException on EnsureSuccessfulAsync on WASM

### ISSUE THREAD

**Issue by alexdrl** [reactiveui/refit#1918]
### Describe the bug 🐞

Getting this error on a .NET 8 Blazor Web App, when render mode gets to WASM.

crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Method not found: System.Threading.Tasks.Task`1<Refit.ApiResponse`1<!0>> Refit.ApiResponse`1.EnsureSuccessfulAsync()
System.MissingMethodException: Method not found: System.Threading.Tasks.Task`1<Refit.ApiResponse`1<!0>> Refit.ApiResponse`1.EnsureSuccessfulAsync()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[<GetEntryAsync>d__14](<GetEntryAsync>d__14& stateMachine)

### Step to reproduce

1. Create sample project with .NET 8 Blazor
2. Add Refit reference to WeatherForecast
3. Call API and ask for EnsureSuccessfulAsync 

### Reproduction repository

https://github.com/reactiveui/refit

### Expected behavior

Method should be present and request being verified

**Comment by PTLMatija** [comment]
We are experiencing a similar issue, while building a request. It does work on some machines but not on the others. Presumably the issue is on Windows10, windows 11 works ok.

```
System.MissingMethodException: Attempted to access a missing method.
   at Refit.SystemTextJsonContentSerializer.ToHttpContent[T](T item)
   at Refit.RequestBuilderImplementation.AddBodyToRequest(RestMethodInfoInternal restMethod, Object param, HttpRequestMessage ret) in c:\temp\releaser\refit\Refit\RequestBuilderImplementation.cs:line 888
   at Refit.RequestBuilderImplementation.<>c__DisplayClass19_0.<BuildRequestFactoryForMethod>b__0(Object[] paramList) in c:\temp\releaser\refit\Refit\RequestBuilderImplementation.cs:line 683
   at Refit.RequestBuilderImplementation.<>c__DisplayClass15_0`2.<<BuildCancellableTaskFuncForMethod>b__0>d.MoveNext() in c:\temp\releaser\refit\Refit\RequestBuilderImplementation.cs:line 320
--- End of stack trace from previous location ---
```

**Comment by TimothyMakkison** [comment]
Hey, does this issue persist when you downgrade refit versions?

**Comment by ghostnguyen** [comment]
I have created a fully support AOT, no reflection and almost identical to Refit's usage.
Just wonder if it has any help?
https://www.nuget.org/packages/HttpClientFiller

**Comment by glennawatson** [comment]
`ApiResponse<T>.EnsureSuccessfulAsync()` is present in current source (`ApiResponse.cs:183`). A `MissingMethodException` / "Method not found" at runtime indicates an assembly version mismatch (duplicate/old Refit DLLs) or WASM trimming stripping the member — not a defect in current source. Ensure a single consistent Refit version, and for trimmed/WASM builds keep the member via a trimmer descriptor. Closing as not reproducible against current source; reopen with a minimal repro on matched versions if it persists.
