### ISSUE TITLE
Refit.ApiException : 500 (Object reference not set to an instance of an object.)

### ISSUE THREAD

**Issue by xplatsolutions** [reactiveui/refit#405]
I have .NET Core library consumed by a .NET Core MVC application and receiving the below exception but it is impossible for me to understand exactly where this is failing

> Message: Refit.ApiException : Response status code does not indicate success: 500 (Object reference not set to an instance of an object.).

This seems as a Refit 4.0.1 bug because I tried with two functional unit tests and HttpClient POST worked fine, as well with using Advanced Rest Client.

```
at Refit.RequestBuilderImplementation.<>c__DisplayClass13_0`1.<<BuildCancellableTaskFuncForMethod>b__0>d.MoveNext() in C:\projects\refit\Refit\RequestBuilderImplementation.cs:line 393
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at AddressScrubberRepository.<ScrubAddressesAsync>d__4.MoveNext() in C:\APP_DATA\Repositories\AddressScrubberRepository.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at AddressScrubberRepository.<ScrubAddressAsync>d__3.MoveNext() in C:\APP_DATA\Repositories\AddressScrubberRepository.cs:line 26
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
--- more related to the application stacktrace
Result Message:	Refit.ApiException : Response status code does not indicate success: 500 (Object reference not set to an instance of an object.).
```

Interface signature.

```
public interface IMelissaApi
    {
        [Post("/batch")]
        Task<IEnumerable<ScrubbedAddressResponseEntity>> BatchScrubAsync([Body] BatchRequestModel batchRequest);
    }
```

xUnit

```
[Fact]
        public async Task should_scrub_address()
        {
            // Arrange
            var melisaApi = RestService.For<IMelissaApi>("http://scrubber.com");
            var repo = new AddressScrubberRepository(melisaApi, "ID");
            var address = new AddressModel
            {
                Street1 = "2AA ROUTE 1",
                City = "Greenville",
                State = "FL",
                Zip = "32331"
            };

            // Act
            var scrubbedAddress = await repo.ScrubAddressAsync(address); // throws exception

            // Assert
            // doesn't matter for example
        }

        [Fact]
        public async Task should_scrub_address_httpclient()
        {
            // Arrange
            var resourceAddress = "http://scrubber.com";
            var address = new AddressModel
            {
                Street1 = "2AA ROUTE 1",
                City = "Greenville",
                State = "FL",
                Zip = "32331"
            };
            var batchRequest = GetBatchRequest();
            batchRequest.Addresses.Add(GetScrubberAddressRequest(Guid.NewGuid().ToString(), address));
            var httpClient = new HttpClient();
            httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            string postBody = batchRequest.ToJson();

            // Act
            HttpResponseMessage response = await httpClient.PostAsync(resourceAddress + "/batch", new StringContent(postBody, Encoding.UTF8, "application/json"));
            string responJsonText = await response.Content.ReadAsStringAsync(); // Response is correct and status is 200

            // Assert
            // doesn't matter for example
        }
```
[UPDATE]
Same exact tests using Refit 4.0.1 for .NET Framework 4.5.2 library works fine.

**Comment by onovotny** [comment]
Happy to look into this; if you can extract an isolated set of tests, that'd be very helpful. Bascially, what does your `BatchRequestModel` look like and what does your `AddressRepository` do? 

What's the shape of the expected response? I'd like to mock it out with the mocking libs we have.

We don't need all of it, just enough to repro the issue.

**Comment by Flohack74** [comment]
I got a strange behaviour here, the exception that comes from empty Content/Headers is not caught and so a NullReferenceException is being thrown:
![image](https://user-images.githubusercontent.com/16186470/53251065-11afdb80-36bc-11e9-82ba-4d797e187b1e.png)

You can see here that the execution jumps straight from the breakpoint to end of method, returning a Nullref exception, instead of an ApiException.

Can it be that the exception handling in ApiException has been optimized and so the catch part is ignored? TBH I have no idea whats going on here. Its exactly not doing what you described by preventing other exceptions happening.

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
