### ISSUE TITLE
[BUG] Using refit to call external API sometimes hang

### ISSUE THREAD

**Issue by nikhorue** [reactiveui/refit#839]
I'm using .NET core 3 and Refit 5.0.23 to call an external API. Sometimes it works fine, but sometimes it hangs and throw error below:

I checked the external API using Postman it returns data very quick and no issues with calling it. But calling through Refit sometimes hang. Has anyone encountered this before?

THanks.

 TaskCanceledException { Task: null, CancellationToken: CancellationToken { IsCancellationRequested: True, CanBeCanceled: True, WaitHandle: "The property accessor threw an exception: ObjectDisposedException" }, TargetSite: Void MoveNext(), StackTrace: "   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Refit.RequestBuilderImplementation.<>c__DisplayClass14_0`2.<<BuildCancellableTaskFuncForMethod>b__0>d.MoveNext() in d:\a\1\s\Refit\RequestBuilderImplementation.cs:line 249
--- End of stack trace from previous location where exception was thrown ---
   at WebAPI.QueryHandler.Handle(Query query, CancellationToken cancellationToken) in D:\WebAPI\Features\QueryHandler.cs:line 79
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at WebAPI.Behaviors.LoggingBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in D:\WebAPI\Behaviors\LoggingBehavior.cs:line 15
   at WebAPI.Behaviors.ValidationBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in D:\WebAPI\Behaviors\ValidatorBehavior.cs:line 54
   at WebAPI.Controllers.Query.GetQuery(Query query) in D:\WebAPI\Features\Query\Query.cs:line 32
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatcher|8_0(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task`1 matcherTask)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at WebAPI.Middleware.CustomExceptionMiddleware.Invoke(HttpContext context) in D:\WebAPI\Middlewares\CustomExceptionMiddleware.cs:line 36", Message: "The operation was canceled.", Data: [], InnerException: IOException { TargetSite: Void ThrowException(System.Net.Sockets.SocketError, System.Threading.CancellationToken), StackTrace: "   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillBufferAsync>g__InternalFillBufferAsync|215_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)", Message: "Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..", Data: [], InnerException: SocketException { Message: "The I/O operation has been aborted because of either a thread exit or an application request.", SocketErrorCode: OperationAborted, ErrorCode: 995, NativeErrorCode: 995, TargetSite: null, StackTrace: null, Data: [], InnerException: null, HelpLink: null, Source: null, HResult: -2147467259 }, HelpLink: null, Source: "System.Net.Sockets", HResult: -2146232800 }, HelpLink: null, Source: "System.Net.Http", HResult: -2146233029 }

**Environment**
- OS:       Windows 10 Pro
- Device:   CPU with i7

**Comment by rsibanez89** [comment]
I've got the same issue ruining it from a Lambda.
It fails less than 1% of the time, but it would be good to understand why it does fail.
`
System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled. ---> System.Net.Sockets.SocketException: Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStreamInternal.<FillBufferAsync>g__InternalFillBufferAsync|38_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStreamInternal.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
`

**Comment by robsonj** [comment]
Following

**Comment by nyongrand** [comment]
I think I got same issue too, I think I will post my unanswered question on other site here:

I use this code to download a zipped file from asp.net core server

```
var content = await service.DownloadZippedImage(filing.Id).ConfigureAwait(false);

// IServiceAPI.cs
[Get("/filings/download/{filingId}")]
Task<HttpContent> DownloadZippedImage(int filingId);
```
In the real code, I call DownloadZippedImage several time during the runtime, the content length is less than 1 MB, but at certain times refit will not return results, so I debug the server but there is no error on the server side, the server actually sent the file.

So I try to execute this code:

```
var content1 = await service.DownloadZippedImage(filing.Id).ConfigureAwait(false);
var content2 = await service.DownloadZippedImage(filing.Id).ConfigureAwait(false);
var content3 = await service.DownloadZippedImage(filing.Id).ConfigureAwait(false);
var content4 = await service.DownloadZippedImage(filing.Id).ConfigureAwait(false);
var content5 = await service.DownloadZippedImage(filing.Id).ConfigureAwait(false);
var content6 = await service.DownloadZippedImage(filing.Id).ConfigureAwait(false);
```
Refit successfully execute several lines (2 or 3) but eventually will hung up without returning anything on the next line until timeout reached, then throwing TaskCanceledException.

This symptom did not occur when I use HttpClient to download the file:

```
private static async TaskHttpContent> DownloadZippedImageAsync(int filingId)
{
    var url = $"http://{Settings.Default.ImagePath}/{filingId}";
    using (var client = new HttpClient())
    {
        var uri = new Uri(url);
        var response = await client.GetAsync(uri).ConfigureAwait(false);
        return response.Content;
    }
}
```
This is the controller code on server:

```
[HttpGet("download/{filingId}")]
public async Task<IActionResult> DownloadZip(int filingId)
{
    var filing = await _context.Filing.FindAsync(filingId);
    if (filing == null)
        return NotFound();

    using var ms = new MemoryStream();
    using (var archive = new ZipArchive(ms, ZipArchiveMode.Create, true))
    {
        for (int page = 1; page <= filing.PageCount; page++)
        {
            var name = $"{filing.TypeId}_{filing.Id}_{page}.jpg";
            var file = @$"{_settings.FilingPath}\{filing.EmployeeId}\{name}";
            if (!System.IO.File.Exists(file))
                return NotFound();

            archive.CreateEntryFromFile(file, name, CompressionLevel.Fastest);
        }
    }

    return File(ms.ToArray(), "application/zip", $"filing_{filing.Id}.zip");
}
```

**Comment by namilkimfree** [comment]
I'am same issue

int count = 0
foreach(var test in tests)
{
 await labTicketApi.LacTicketRegisterComplete(test );
 ++count
}
count = 2 is hang..

Throw TaskCanceledException

**Comment by namilkimfree** [comment]
@anaisbetts

**Comment by robsonj** [comment]
We actually found our issue to be related to Windows trying to start up a http proxy service for the first service that started on a server. That would cause a hang, on a restart, everything worked fine and subsequent services were able to use refit without issue.

The fix involved passing a WinHttpHandler to the refit client when running on windows

**Comment by namilkimfree** [comment]
@robsonj fixed this issue? 
When is the distribution? Or can I use a repository project rather than nuget?

Thank you

**Comment by nyongrand** [comment]
> We actually found our issue to be related to Windows trying to start up a http proxy service for the first service that started on a server. That would cause a hang, on a restart, everything worked fine and subsequent services were able to use refit without issue.
> 

Do you mean server restart, or app restart,

> The fix involved passing a WinHttpHandler to the refit client when running on windows

Can you give an example

**Comment by robsonj** [comment]
Service restart, here is how we configure our Rest client...

```
            HttpMessageHandler handler = null;
            if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
            {
                handler = new WinHttpHandler()
                {
                    WindowsProxyUsePolicy = WindowsProxyUsePolicy.DoNotUseProxy,
                    ClientCertificateOption = ClientCertificateOption.Automatic,
                    ServerCertificateValidationCallback = (message, cert, chain, errors) => true,
                    Proxy = null
                };
            }
            else
            {
                handler = new HttpClientHandler
                {
                    ClientCertificateOptions = ClientCertificateOption.Automatic,
                    ServerCertificateCustomValidationCallback = (message, cert, chain, errors) => true,
                    Proxy = null
                };
            }

            var httpClient = new HttpClient(handler)
            {
                BaseAddress = new Uri(source),
                Timeout = timeout
            };

            return Refit.RestService.For<ICentralConfigService>(httpClient,
                                                                new RefitSettings
                                                                {
                                                                    ContentSerializer = new XmlContentSerializer()
                                                                });
```

**Comment by robsonj** [comment]
This may not solve your issue as this only affected **the first service** to start on the box. This endpoint only gets hit once per process lifecycle typically.

**Comment by namilkimfree** [comment]
I'm not use winhttphandler. using default winhttphandler on windows?

**Comment by robsonj** [comment]
This is the WinhttpHandler we are using... https://docs.microsoft.com/en-us/dotnet/api/system.net.http.winhttphandler?view=dotnet-plat-ext-3.1

**Comment by joe-ifit** [comment]
I am seeing this issue consistently after upgrading from 2.4.1 -> 5.1.67.  I made sure that our `awaits` are using `ConfigureAwait(false)` but I am still seeing this issue.  I did notice that in the refit code there is a call with `ConfigureAwait(false)` missing:

https://github.com/reactiveui/refit/blob/4c786b27cbbabcd108be8e9274c8b6527c1742ca/Refit/RequestBuilderImplementation.cs#L258

I am having trouble building the code locally to test, but this could be leading to some deadlocks

**Comment by jay1891** [comment]
The same issue here. The strange this is, I can call 2 times after each other without a problem. The third time it always hangs.

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.

**Comment by brud** [comment]
Hi 
I've upgraded refit from v5 to v6 and got this error:
```
System.Threading.Tasks.TaskCanceledException: The operation was canceled. 
---> System.IO.IOException: Unable to read data from the transport connection: interrupted.
---> System.Net.Sockets.SocketException: interrupted
```

**Comment by mattmas** [comment]
FYI for anyone else who got this issue and wound up here.
I had this issue - even with Refit 6.0. I would get two successful POSTs, and then the third would hang up until there was a 100 second timeout that bubbled up as a TaskCanceledException.

Here's what it was at the end of the day: The definition of the Refit interface call.
Because the POST was not returning anything meaningful, but I DID want to get the status code, I had found other guidance to define the method as:

Task<HttpResponseMessage> AddActualValue(string projectId, ActualObject o);

The answer was to change to:
Task<ApiResponse<string>> AddActualValue(string projectId, ActualObject o);

Suddenly everything was fine again. Not sure why the issue happened the way it did, but spent a day or so fighting it, so I figured I'd pass it on..

**Comment by CurlyBytes** [comment]
i just revise @mattmas  answer, to work properly you mas add a body serialize URL encoded in refit 6.0
  Task<ApiResponse<WrapperAbsenceResponse>> PostAbsencesAsync([Body(**BodySerializationMethod.UrlEncoded)**] PostAbsencesRequest postAbsences); 
  
  this for POST type API

**Comment by cstamati** [comment]
I am using Refit 6.3.2 in Unity Engine 2022. I created a library in visual studio that is using refit to make API calls since in Unity I don't know ho to use code generators yet. It works great but sometimes it hangs with POST apis:
<img width="292" alt="image" src="https://user-images.githubusercontent.com/91951421/185949099-aed72ff4-d20a-49c4-a9a3-eb39805e71df.png">
