### ISSUE TITLE
[Hangfire] Hangfire asp.net core refit 

### ISSUE THREAD

**Issue by tienvd1994** [reactiveui/refit#891]
I use refit (https://github.com/reactiveui/refit) inside BackgroundJob.Enqueue of Hangfire (https://github.com/HangfireIO/Hangfire) to call request from service other. But return status code 400. Sorry my english is very bad. Pls support me this error.
```
Refit.ApiException: Response status code does not indicate success: 400 (Bad Request).
   at Refit.RequestBuilderImplementation.<>c__DisplayClass20_0.<<BuildVoidTaskFuncForMethod>b__0>d.MoveNext() in d:\a\1\s\Refit\RequestBuilderImplementation.cs:line 773
--- End of stack trace from previous location where exception was thrown ---
   at INKA.Order.Infrastructure.Mediators.NotificationHandlers.OrderDeliveryReminderNotificationHandler.Handle(OrderDeliveryReminderNotification notification, CancellationToken cancellationToken) in E:\Works\Projects\inka_saas\INKA.Order.Infrastructure\Mediators\NotificationHandlers\OrderDeliveryReminderNotificationHandler.cs:line 74
   at MediatR.Mediator.PublishCore(IEnumerable`1 allHandlers, INotification notification, CancellationToken cancellationToken)
   at INKA.Order.Infrastructure.Handlers.Order.OrderInsertCommandHandler.SendNotification(String orderId, String orderCode, List`1 installations, List`1 shippings) in E:\Works\Projects\inka_saas\INKA.Order.Infrastructure\Handlers\Order\OrderCommandHandler.cs:line 533
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
```

**Comment by Dreamescaper** [comment]
Why do you think that 400 error is Refit issue?

**Comment by clairernovotny** [comment]
Closing due to age. Please try Refit v6 and reopen if still an issue.
