### ISSUE TITLE
[BUG] TaskCanceledException when sending large-ish arrays with System.Text.Json

### ISSUE THREAD

**Issue by EricStG** [reactiveui/refit#921]
**Describe the bug**
When submitting a string array of about 25k single-char items in the body of the request with the System.Text.Json serializer, I get the following exception:

```
System.Threading.Tasks.TaskCanceledException
  HResult=0x8013153B
  Message=The operation was canceled.
  Source=System.Net.Http
  StackTrace:
   at System.Net.Http.HttpConnection.<SendAsyncCore>d__53.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpConnectionPool.<SendWithNtConnectionAuthAsync>d__48.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpConnectionPool.<SendWithRetryAsync>d__47.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.RedirectHandler.<SendAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__70.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Refit.RequestBuilderImplementation.<>c__DisplayClass23_0.<<BuildVoidTaskFuncForMethod>b__0>d.MoveNext() in /_/Refit/RequestBuilderImplementation.cs:line 788
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Client.Program.<Main>d__0.MoveNext() in C:\Users\echal\source\repos\RefitJsonText\Client\Program.cs:line 24

Inner Exception 1:
IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..

Inner Exception 2:
SocketException: The I/O operation has been aborted because of either a thread exit or an application request.
```

The error does not happen for a smaller array size (20) or when using Newtonsoft.

**Steps To Reproduce**

Interface:
```csharp
public interface ITestService
{
    [Post("/api/test")]
    Task PostAsync([Body]string[] values);
}
```

Usage
```csharp
var settings = new RefitSettings(new SystemTextJsonContentSerializer());
var client = RestService.For<ITestService>("http://localhost:5000/", settings);

// Works: const int count = 20000;
const int count = 25000;
const string value = "a";
var values = Enumerable.Repeat(value, count).ToArray();
await client.PostAsync(values);
```
Full repro at https://github.com/EricStG/RefitJsonText

**Expected behavior**

The service should receive the payload, or I should get an exception telling me what I'm doing wrong.

**Screenshots**

N/A

**Environment**

- OS:       Windows 10
- Device:   Desktop
- Version:   5.1.67
- Working Version: 5.1.67

**Additional context**

**Comment by clairernovotny** [comment]
Should be fixed in Refit 6. Please try the latest and re-open if still an issue.
