### ISSUE TITLE
[BUG] No default value for RefitSettings parameter when using ApiException.Create()

### ISSUE THREAD

**Issue by jfcere** [reactiveui/refit#922]
**Describe the bug**

When using `ApiException.Create()` with a serialized `HttpResponseMessage.Content` and we do not provide the `RefitSettings` optional parameter, the property `RefitSettings` is never set with the default values such as in the `RefitSettings` constructor.

Therefore using `ValidationApiException.Create(ApiException exception)` will throw `NullReferenceException: Object not set to an instance or an object` in `ApiException.GetContentAsAsync<T>()` because `RefitSettings` is null and cannot call `RefitSettings.ContentSerializer.DeserializeAsync<T>()`.

The workaround is to provide `new RefitSettings()` as a parameter but since it is optional, I believe it should automatically fall back to its default constructor value.

**Steps To Reproduce**

The following example do not provide `new RefitSettings()` as a parameter of the `ApiException.Create()` method.

```csharp
var responseMessage = new HttpResponseMessage(HttpStatusCode.BadRequest)
{
    Content = await new NewtonsoftJsonContentSerializer().SerializeAsync(new ProblemDetails())
};
var apiException = await ApiException.Create(new HttpRequestMessage(), HttpMethod.Get, responseMessage);
var validationApiException = await ValidationApiException.Create(apiException);
```

Throws with the following stack trace:
```
 System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Refit
  StackTrace:
   at Refit.ApiException.<GetContentAsAsync>d__33`1.MoveNext() in /_/Refit/ApiException.cs:line 38
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Refit.ValidationApiException.<Create>d__1.MoveNext() in /_/Refit/ValidationApiException.cs:line 27
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at XTests.Unit.ServiceTests.GivenTestExample.<WhenSomethingThenSomethingElse>d__20.MoveNext() in C:\Example\XTests\Unit\ServiceTests\GivenTestExample.cs:line 100
```

It can be fixed by providing `new RefitSettings()` when using `ApiException.Create()` method:

```csharp
var apiException = await ApiException.Create(new HttpRequestMessage(), HttpMethod.Get, responseMessage, new RefitSettings());
```

**Expected behavior**

When `RefitSettings` parameter is not provided in the `ApiException.Create` method it should use the default values set in the `RefitSettings` constructor to avoid NullReference exception.

**Screenshots**

Not applicable.

**Environment**

- OS: Windows 10 Profesionnal 64 bits 
- Device:  Desktop 
- Version:  5.1.67 
- Working Version: 5.1.67 

**Additional context**

No additional information.

**Comment by qin-guan** [comment]
are there updates to this issue?

**Comment by clairernovotny** [comment]
This should be fixed in v6. Please re-open if an issue.
